-- NLE Best Deal — NLE Rewards
-- À exécuter UNE FOIS dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.nle_reward_profiles (
  id uuid primary key default gen_random_uuid(),
  referral_code text not null unique,
  session_id text not null,
  full_name text,
  phone text,
  points integer not null default 0 check (points >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nle_reward_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  referral_code text,
  session_id text,
  channel text,
  task text,
  points_requested integer,
  landing_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.nle_reward_claims (
  id uuid primary key default gen_random_uuid(),
  referral_code text not null,
  session_id text not null,
  full_name text,
  phone_number text not null,
  network text not null check (network in ('Digicel','Natcom')),
  points_used integer not null check (points_used > 0),
  amount_htg integer not null check (amount_htg > 0),
  status text not null default 'pending'
    check (status in ('pending','approved','completed','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists nle_reward_events_ref_idx
  on public.nle_reward_events(referral_code, created_at desc);

create index if not exists nle_reward_claims_ref_idx
  on public.nle_reward_claims(referral_code, created_at desc);

alter table public.nle_reward_profiles enable row level security;
alter table public.nle_reward_events enable row level security;
alter table public.nle_reward_claims enable row level security;

drop policy if exists "nle rewards profile insert" on public.nle_reward_profiles;
create policy "nle rewards profile insert"
on public.nle_reward_profiles for insert to anon, authenticated with check (true);

drop policy if exists "nle rewards event insert" on public.nle_reward_events;
create policy "nle rewards event insert"
on public.nle_reward_events for insert to anon, authenticated with check (true);

drop policy if exists "nle rewards claim insert" on public.nle_reward_claims;
create policy "nle rewards claim insert"
on public.nle_reward_claims for insert to anon, authenticated with check (true);

drop policy if exists "nle rewards profiles authenticated read" on public.nle_reward_profiles;
create policy "nle rewards profiles authenticated read"
on public.nle_reward_profiles for select to authenticated using (true);

drop policy if exists "nle rewards events authenticated read" on public.nle_reward_events;
create policy "nle rewards events authenticated read"
on public.nle_reward_events for select to authenticated using (true);

drop policy if exists "nle rewards claims authenticated read" on public.nle_reward_claims;
create policy "nle rewards claims authenticated read"
on public.nle_reward_claims for select to authenticated using (true);

drop policy if exists "nle rewards claims authenticated update" on public.nle_reward_claims;
create policy "nle rewards claims authenticated update"
on public.nle_reward_claims for update to authenticated using (true) with check (true);

drop policy if exists "nle rewards profiles authenticated update" on public.nle_reward_profiles;
create policy "nle rewards profiles authenticated update"
on public.nle_reward_profiles for update to authenticated using (true) with check (true);
